### ISSUE TITLE
Windows Lumia 950 - Win 10

### ISSUE THREAD

**Issue by puppeteer701vungle** [rbiggs/gestura#1]
`e['touches']` is undefined when binding to tap events.

**Comment by rbiggs** [comment]
Since all current evergreen browsers are now supporting pointer events:https://github.com/w3c/pointerevents,  I'd recommend you use a pointer events polypill for the Lumia: https://github.com/jquery/PEP. Since all browser venders have finally gotten behind pointer events, I am not going to maintain this repo any further. I created it long before there was any agreement on how to handle events across desktop and mobile. Now there's an agreement, so this isn't really necessary.
